parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Guttmann\NautCli\:
    resource: '../src/*'
    exclude: '../src/{Entity,Repository}'

  Guttmann\NautCli\Service\FetchLatestService:
    public: true

  Guttmann\NautCli\Service\DeployService:
    public: true

  Guttmann\NautCli\Service\DeployLogService:
    public: true

  Guttmann\NautCli\Service\SnapshotService:
    public: true

  Guttmann\NautCli\Service\SnapshotLogService:
    public: true

  naut.fetch:
    alias: Guttmann\NautCli\Service\FetchLatestService
    public: true

  naut.deploy:
    alias: Guttmann\NautCli\Service\DeployService
    public: true

  naut.deploy_log:
    alias: Guttmann\NautCli\Service\DeployLogService
    public: true

  naut.snapshot:
    alias: Guttmann\NautCli\Service\SnapshotService
    public: true

  naut.snapshot_log:
    alias: Guttmann\NautCli\Service\SnapshotLogService
    public: true

framework:
  secret: ''